# Generated by Django 5.2 on 2025-06-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(default="Unknown", max_length=50, verbose_name="Страна"),
        ),
    ]
