# Generated by Django 4.2.2 on 2025-06-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=50, verbose_name="Страна"),
        ),
    ]
