# Generated by Django 5.2 on 2025-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок поста")),
                ("content", models.TextField(verbose_name="Содержимое поста")),
                (
                    "preview_image",
                    models.ImageField(blank=True, null=True, upload_to="catalog/foto", verbose_name="Изображение"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Дата публикации")),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликована?")),
                ("views_count", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
