# Generated by Django 4.2.2 on 2025-06-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication",
            field=models.BooleanField(default=False, verbose_name="Опубликовано?"),
        ),
    ]
