# Generated by Django 4.2.2 on 2025-06-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="publication",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
